/* verilator tracing_off */
// Generated by PeakRDL-regblock - A free and open-source SystemVerilog generator
//  https://github.com/SystemRDL/PeakRDL-regblock

package alu_accel_csr_pkg;

    localparam ALU_ACCEL_CSR_DATA_WIDTH = 32;
    localparam ALU_ACCEL_CSR_MIN_ADDR_WIDTH = 5;
    localparam ALU_ACCEL_CSR_SIZE = 'h20;

    typedef struct {
        logic next;
    } status_r__BUSY__in_t;

    typedef struct {
        logic next;
    } status_r__FIFO_FULL__in_t;

    typedef struct {
        logic next;
    } status_r__FIFO_EMPTY__in_t;

    typedef struct {
        logic [7:0] next;
    } status_r__DONE_CNT__in_t;

    typedef struct {
        status_r__BUSY__in_t BUSY;
        status_r__FIFO_FULL__in_t FIFO_FULL;
        status_r__FIFO_EMPTY__in_t FIFO_EMPTY;
        status_r__DONE_CNT__in_t DONE_CNT;
    } status_r__in_t;

    typedef struct {
        logic [7:0] next;
    } result_r__Y__in_t;

    typedef struct {
        result_r__Y__in_t Y;
    } result_r__in_t;

    typedef struct {
        logic next;
    } flags_r__ZF__in_t;

    typedef struct {
        logic next;
    } flags_r__CF__in_t;

    typedef struct {
        logic next;
    } flags_r__NF__in_t;

    typedef struct {
        logic next;
    } flags_r__VF__in_t;

    typedef struct {
        flags_r__ZF__in_t ZF;
        flags_r__CF__in_t CF;
        flags_r__NF__in_t NF;
        flags_r__VF__in_t VF;
    } flags_r__in_t;

    typedef struct {
        status_r__in_t status;
        result_r__in_t result;
        flags_r__in_t flags;
    } alu_accel_csr__in_t;

    typedef struct {
        logic value;
    } ctrl_r__SRC__out_t;

    typedef struct {
        logic value;
    } ctrl_r__GO__out_t;

    typedef struct {
        ctrl_r__SRC__out_t SRC;
        ctrl_r__GO__out_t GO;
    } ctrl_r__out_t;

    typedef struct {
        logic [2:0] value;
    } op_r__OP__out_t;

    typedef struct {
        op_r__OP__out_t OP;
    } op_r__out_t;

    typedef struct {
        logic [7:0] value;
    } operand_a_r__A__out_t;

    typedef struct {
        operand_a_r__A__out_t A;
    } operand_a_r__out_t;

    typedef struct {
        logic [7:0] value;
    } operand_b_r__B__out_t;

    typedef struct {
        operand_b_r__B__out_t B;
    } operand_b_r__out_t;

    typedef struct {
        logic value;
    } fifo_push_r__PUSH__out_t;

    typedef struct {
        logic [2:0] value;
    } fifo_push_r__OP__out_t;

    typedef struct {
        logic [7:0] value;
    } fifo_push_r__A__out_t;

    typedef struct {
        logic [7:0] value;
    } fifo_push_r__B__out_t;

    typedef struct {
        fifo_push_r__PUSH__out_t PUSH;
        fifo_push_r__OP__out_t OP;
        fifo_push_r__A__out_t A;
        fifo_push_r__B__out_t B;
    } fifo_push_r__out_t;

    typedef struct {
        ctrl_r__out_t ctrl;
        op_r__out_t op;
        operand_a_r__out_t operand_a;
        operand_b_r__out_t operand_b;
        fifo_push_r__out_t fifo_push;
    } alu_accel_csr__out_t;
endpackage
