/* verilator lint_off MULTIDRIVEN */ /* verilator lint_off GENUNNAMED */ /* verilator tracing_off */
// Generated by PeakRDL-regblock - A free and open-source SystemVerilog generator
//  https://github.com/SystemRDL/PeakRDL-regblock

module alu_accel_csr (
        input wire clk,
        input wire rst_n,

        input wire s_apb_psel,
        input wire s_apb_penable,
        input wire s_apb_pwrite,
        input wire [2:0] s_apb_pprot,
        input wire [4:0] s_apb_paddr,
        input wire [31:0] s_apb_pwdata,
        input wire [3:0] s_apb_pstrb,
        output logic s_apb_pready,
        output logic [31:0] s_apb_prdata,
        output logic s_apb_pslverr,

        input alu_accel_csr_pkg::alu_accel_csr__in_t hwif_in,
        output alu_accel_csr_pkg::alu_accel_csr__out_t hwif_out
    );

    //--------------------------------------------------------------------------
    // CPU Bus interface logic
    //--------------------------------------------------------------------------
    logic cpuif_req;
    logic cpuif_req_is_wr;
    logic [4:0] cpuif_addr;
    logic [31:0] cpuif_wr_data;
    logic [31:0] cpuif_wr_biten;
    logic cpuif_req_stall_wr;
    logic cpuif_req_stall_rd;

    logic cpuif_rd_ack;
    logic cpuif_rd_err;
    logic [31:0] cpuif_rd_data;

    logic cpuif_wr_ack;
    logic cpuif_wr_err;

    // Request
    logic is_active;
    always_ff @(posedge clk) begin
        if(~rst_n) begin
            is_active <= '0;
            cpuif_req <= '0;
            cpuif_req_is_wr <= '0;
            cpuif_addr <= '0;
            cpuif_wr_data <= '0;
            cpuif_wr_biten <= '0;
        end else begin
            if(~is_active) begin
                if(s_apb_psel) begin
                    is_active <= '1;
                    cpuif_req <= '1;
                    cpuif_req_is_wr <= s_apb_pwrite;
                    cpuif_addr <= {s_apb_paddr[4:2], 2'b0};
                    cpuif_wr_data <= s_apb_pwdata;
                    for(int i=0; i<4; i++) begin
                        cpuif_wr_biten[i*8 +: 8] <= {8{s_apb_pstrb[i]}};
                    end
                end
            end else begin
                cpuif_req <= '0;
                if(cpuif_rd_ack || cpuif_wr_ack) begin
                    is_active <= '0;
                end
            end
        end
    end

    // Response
    assign s_apb_pready = cpuif_rd_ack | cpuif_wr_ack;
    assign s_apb_prdata = cpuif_rd_data;
    assign s_apb_pslverr = cpuif_rd_err | cpuif_wr_err;

    logic cpuif_req_masked;

    // Read & write latencies are balanced. Stalls not required
    assign cpuif_req_stall_rd = '0;
    assign cpuif_req_stall_wr = '0;
    assign cpuif_req_masked = cpuif_req
                            & !(!cpuif_req_is_wr & cpuif_req_stall_rd)
                            & !(cpuif_req_is_wr & cpuif_req_stall_wr);

    //--------------------------------------------------------------------------
    // Address Decode
    //--------------------------------------------------------------------------
    typedef struct {
        logic ctrl;
        logic status;
        logic op;
        logic operand_a;
        logic operand_b;
        logic result;
        logic flags;
        logic fifo_push;
    } decoded_reg_strb_t;
    decoded_reg_strb_t decoded_reg_strb;
    logic decoded_err;
    logic [4:0] decoded_addr;
    logic decoded_req;
    logic decoded_req_is_wr;
    logic [31:0] decoded_wr_data;
    logic [31:0] decoded_wr_biten;

    always_comb begin
        automatic logic is_valid_addr;
        automatic logic is_valid_rw;
        is_valid_addr = '1; // No valid address check
        is_valid_rw = '1; // No valid RW check
        decoded_reg_strb.ctrl = cpuif_req_masked & (cpuif_addr == 5'h0);
        decoded_reg_strb.status = cpuif_req_masked & (cpuif_addr == 5'h4) & !cpuif_req_is_wr;
        decoded_reg_strb.op = cpuif_req_masked & (cpuif_addr == 5'h8);
        decoded_reg_strb.operand_a = cpuif_req_masked & (cpuif_addr == 5'hc);
        decoded_reg_strb.operand_b = cpuif_req_masked & (cpuif_addr == 5'h10);
        decoded_reg_strb.result = cpuif_req_masked & (cpuif_addr == 5'h14) & !cpuif_req_is_wr;
        decoded_reg_strb.flags = cpuif_req_masked & (cpuif_addr == 5'h18) & !cpuif_req_is_wr;
        decoded_reg_strb.fifo_push = cpuif_req_masked & (cpuif_addr == 5'h1c);
        decoded_err = '0;
    end

    // Pass down signals to next stage
    assign decoded_addr = cpuif_addr;
    assign decoded_req = cpuif_req_masked;
    assign decoded_req_is_wr = cpuif_req_is_wr;
    assign decoded_wr_data = cpuif_wr_data;
    assign decoded_wr_biten = cpuif_wr_biten;

    //--------------------------------------------------------------------------
    // Field logic
    //--------------------------------------------------------------------------
    typedef struct {
        struct {
            struct {
                logic next;
                logic load_next;
            } SRC;
            struct {
                logic next;
                logic load_next;
            } GO;
        } ctrl;
        struct {
            struct {
                logic [2:0] next;
                logic load_next;
            } OP;
        } op;
        struct {
            struct {
                logic [7:0] next;
                logic load_next;
            } A;
        } operand_a;
        struct {
            struct {
                logic [7:0] next;
                logic load_next;
            } B;
        } operand_b;
        struct {
            struct {
                logic next;
                logic load_next;
            } PUSH;
            struct {
                logic [2:0] next;
                logic load_next;
            } OP;
            struct {
                logic [7:0] next;
                logic load_next;
            } A;
            struct {
                logic [7:0] next;
                logic load_next;
            } B;
        } fifo_push;
    } field_combo_t;
    field_combo_t field_combo;

    typedef struct {
        struct {
            struct {
                logic value;
            } SRC;
            struct {
                logic value;
            } GO;
        } ctrl;
        struct {
            struct {
                logic [2:0] value;
            } OP;
        } op;
        struct {
            struct {
                logic [7:0] value;
            } A;
        } operand_a;
        struct {
            struct {
                logic [7:0] value;
            } B;
        } operand_b;
        struct {
            struct {
                logic value;
            } PUSH;
            struct {
                logic [2:0] value;
            } OP;
            struct {
                logic [7:0] value;
            } A;
            struct {
                logic [7:0] value;
            } B;
        } fifo_push;
    } field_storage_t;
    field_storage_t field_storage;

    // Field: alu_accel_csr.ctrl.SRC
    always_comb begin
        automatic logic [0:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.ctrl.SRC.value;
        load_next_c = '0;
        if(decoded_reg_strb.ctrl && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.ctrl.SRC.value & ~decoded_wr_biten[0:0]) | (decoded_wr_data[0:0] & decoded_wr_biten[0:0]);
            load_next_c = '1;
        end
        field_combo.ctrl.SRC.next = next_c;
        field_combo.ctrl.SRC.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(~rst_n) begin
            field_storage.ctrl.SRC.value <= 1'h0;
        end else begin
            if(field_combo.ctrl.SRC.load_next) begin
                field_storage.ctrl.SRC.value <= field_combo.ctrl.SRC.next;
            end
        end
    end
    assign hwif_out.ctrl.SRC.value = field_storage.ctrl.SRC.value;
    // Field: alu_accel_csr.ctrl.GO
    always_comb begin
        automatic logic [0:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.ctrl.GO.value;
        load_next_c = '0;
        if(decoded_reg_strb.ctrl && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.ctrl.GO.value & ~decoded_wr_biten[1:1]) | (decoded_wr_data[1:1] & decoded_wr_biten[1:1]);
            load_next_c = '1;
        end else begin // singlepulse clears back to 0
            next_c = '0;
            load_next_c = '1;
        end
        field_combo.ctrl.GO.next = next_c;
        field_combo.ctrl.GO.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(~rst_n) begin
            field_storage.ctrl.GO.value <= 1'h0;
        end else begin
            if(field_combo.ctrl.GO.load_next) begin
                field_storage.ctrl.GO.value <= field_combo.ctrl.GO.next;
            end
        end
    end
    assign hwif_out.ctrl.GO.value = field_storage.ctrl.GO.value;
    // Field: alu_accel_csr.op.OP
    always_comb begin
        automatic logic [2:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.op.OP.value;
        load_next_c = '0;
        if(decoded_reg_strb.op && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.op.OP.value & ~decoded_wr_biten[2:0]) | (decoded_wr_data[2:0] & decoded_wr_biten[2:0]);
            load_next_c = '1;
        end
        field_combo.op.OP.next = next_c;
        field_combo.op.OP.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(~rst_n) begin
            field_storage.op.OP.value <= 3'h0;
        end else begin
            if(field_combo.op.OP.load_next) begin
                field_storage.op.OP.value <= field_combo.op.OP.next;
            end
        end
    end
    assign hwif_out.op.OP.value = field_storage.op.OP.value;
    // Field: alu_accel_csr.operand_a.A
    always_comb begin
        automatic logic [7:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.operand_a.A.value;
        load_next_c = '0;
        if(decoded_reg_strb.operand_a && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.operand_a.A.value & ~decoded_wr_biten[7:0]) | (decoded_wr_data[7:0] & decoded_wr_biten[7:0]);
            load_next_c = '1;
        end
        field_combo.operand_a.A.next = next_c;
        field_combo.operand_a.A.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(~rst_n) begin
            field_storage.operand_a.A.value <= 8'h0;
        end else begin
            if(field_combo.operand_a.A.load_next) begin
                field_storage.operand_a.A.value <= field_combo.operand_a.A.next;
            end
        end
    end
    assign hwif_out.operand_a.A.value = field_storage.operand_a.A.value;
    // Field: alu_accel_csr.operand_b.B
    always_comb begin
        automatic logic [7:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.operand_b.B.value;
        load_next_c = '0;
        if(decoded_reg_strb.operand_b && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.operand_b.B.value & ~decoded_wr_biten[7:0]) | (decoded_wr_data[7:0] & decoded_wr_biten[7:0]);
            load_next_c = '1;
        end
        field_combo.operand_b.B.next = next_c;
        field_combo.operand_b.B.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(~rst_n) begin
            field_storage.operand_b.B.value <= 8'h0;
        end else begin
            if(field_combo.operand_b.B.load_next) begin
                field_storage.operand_b.B.value <= field_combo.operand_b.B.next;
            end
        end
    end
    assign hwif_out.operand_b.B.value = field_storage.operand_b.B.value;
    // Field: alu_accel_csr.fifo_push.PUSH
    always_comb begin
        automatic logic [0:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.fifo_push.PUSH.value;
        load_next_c = '0;
        if(decoded_reg_strb.fifo_push && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.fifo_push.PUSH.value & ~decoded_wr_biten[0:0]) | (decoded_wr_data[0:0] & decoded_wr_biten[0:0]);
            load_next_c = '1;
        end else begin // singlepulse clears back to 0
            next_c = '0;
            load_next_c = '1;
        end
        field_combo.fifo_push.PUSH.next = next_c;
        field_combo.fifo_push.PUSH.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(~rst_n) begin
            field_storage.fifo_push.PUSH.value <= 1'h0;
        end else begin
            if(field_combo.fifo_push.PUSH.load_next) begin
                field_storage.fifo_push.PUSH.value <= field_combo.fifo_push.PUSH.next;
            end
        end
    end
    assign hwif_out.fifo_push.PUSH.value = field_storage.fifo_push.PUSH.value;
    // Field: alu_accel_csr.fifo_push.OP
    always_comb begin
        automatic logic [2:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.fifo_push.OP.value;
        load_next_c = '0;
        if(decoded_reg_strb.fifo_push && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.fifo_push.OP.value & ~decoded_wr_biten[3:1]) | (decoded_wr_data[3:1] & decoded_wr_biten[3:1]);
            load_next_c = '1;
        end
        field_combo.fifo_push.OP.next = next_c;
        field_combo.fifo_push.OP.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(~rst_n) begin
            field_storage.fifo_push.OP.value <= 3'h0;
        end else begin
            if(field_combo.fifo_push.OP.load_next) begin
                field_storage.fifo_push.OP.value <= field_combo.fifo_push.OP.next;
            end
        end
    end
    assign hwif_out.fifo_push.OP.value = field_storage.fifo_push.OP.value;
    // Field: alu_accel_csr.fifo_push.A
    always_comb begin
        automatic logic [7:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.fifo_push.A.value;
        load_next_c = '0;
        if(decoded_reg_strb.fifo_push && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.fifo_push.A.value & ~decoded_wr_biten[11:4]) | (decoded_wr_data[11:4] & decoded_wr_biten[11:4]);
            load_next_c = '1;
        end
        field_combo.fifo_push.A.next = next_c;
        field_combo.fifo_push.A.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(~rst_n) begin
            field_storage.fifo_push.A.value <= 8'h0;
        end else begin
            if(field_combo.fifo_push.A.load_next) begin
                field_storage.fifo_push.A.value <= field_combo.fifo_push.A.next;
            end
        end
    end
    assign hwif_out.fifo_push.A.value = field_storage.fifo_push.A.value;
    // Field: alu_accel_csr.fifo_push.B
    always_comb begin
        automatic logic [7:0] next_c;
        automatic logic load_next_c;
        next_c = field_storage.fifo_push.B.value;
        load_next_c = '0;
        if(decoded_reg_strb.fifo_push && decoded_req_is_wr) begin // SW write
            next_c = (field_storage.fifo_push.B.value & ~decoded_wr_biten[19:12]) | (decoded_wr_data[19:12] & decoded_wr_biten[19:12]);
            load_next_c = '1;
        end
        field_combo.fifo_push.B.next = next_c;
        field_combo.fifo_push.B.load_next = load_next_c;
    end
    always_ff @(posedge clk) begin
        if(~rst_n) begin
            field_storage.fifo_push.B.value <= 8'h0;
        end else begin
            if(field_combo.fifo_push.B.load_next) begin
                field_storage.fifo_push.B.value <= field_combo.fifo_push.B.next;
            end
        end
    end
    assign hwif_out.fifo_push.B.value = field_storage.fifo_push.B.value;

    //--------------------------------------------------------------------------
    // Write response
    //--------------------------------------------------------------------------
    assign cpuif_wr_ack = decoded_req & decoded_req_is_wr;
    // Writes are always granted with no error response
    assign cpuif_wr_err = '0;

    //--------------------------------------------------------------------------
    // Readback
    //--------------------------------------------------------------------------

    logic [4:0] rd_mux_addr;
    assign rd_mux_addr = decoded_addr;

    logic readback_err;
    logic readback_done;
    logic [31:0] readback_data;
    always_comb begin
        automatic logic [31:0] readback_data_var;
        readback_data_var = '0;
        if(rd_mux_addr == 5'h0) begin
            readback_data_var[0] = field_storage.ctrl.SRC.value;
            readback_data_var[1] = field_storage.ctrl.GO.value;
        end
        if(rd_mux_addr == 5'h4) begin
            readback_data_var[0] = hwif_in.status.BUSY.next;
            readback_data_var[1] = hwif_in.status.FIFO_FULL.next;
            readback_data_var[2] = hwif_in.status.FIFO_EMPTY.next;
            readback_data_var[10:3] = hwif_in.status.DONE_CNT.next;
        end
        if(rd_mux_addr == 5'h8) begin
            readback_data_var[2:0] = field_storage.op.OP.value;
        end
        if(rd_mux_addr == 5'hc) begin
            readback_data_var[7:0] = field_storage.operand_a.A.value;
        end
        if(rd_mux_addr == 5'h10) begin
            readback_data_var[7:0] = field_storage.operand_b.B.value;
        end
        if(rd_mux_addr == 5'h14) begin
            readback_data_var[7:0] = hwif_in.result.Y.next;
        end
        if(rd_mux_addr == 5'h18) begin
            readback_data_var[0] = hwif_in.flags.ZF.next;
            readback_data_var[1] = hwif_in.flags.CF.next;
            readback_data_var[2] = hwif_in.flags.NF.next;
            readback_data_var[3] = hwif_in.flags.VF.next;
        end
        if(rd_mux_addr == 5'h1c) begin
            readback_data_var[3:1] = field_storage.fifo_push.OP.value;
            readback_data_var[11:4] = field_storage.fifo_push.A.value;
            readback_data_var[19:12] = field_storage.fifo_push.B.value;
        end
        readback_data = readback_data_var;
        readback_done = decoded_req & ~decoded_req_is_wr;
        readback_err = '0;
    end

    assign cpuif_rd_ack = readback_done;
    assign cpuif_rd_data = readback_data;
    assign cpuif_rd_err = readback_err;
endmodule
