# CDC timing exceptions for demo_cdc_open_top (XDC)
# Generated by `rb cdc --emit-constraints` from the verified
# crossing set — do not hand-edit; regenerate when the RTL changes.
# Scoped: cells are IP-relative; apply with SCOPED_TO_REF so every instantiation inherits these (top clock defs/groups belong to the parent).

set_max_delay -datapath_only 7.5 -from [get_cells -hierarchical * -filter {IS_SEQUENTIAL}] -to [get_cells u_flag_sync/* -filter {IS_SEQUENTIAL}]
set_max_delay -datapath_only 7.5 -from [get_cells u_gray_bus/* -filter {IS_SEQUENTIAL}] -to [get_cells u_gray_bus/u_gray_sync/* -filter {IS_SEQUENTIAL}]
set_bus_skew 7.5 -from [get_cells u_gray_bus/* -filter {IS_SEQUENTIAL}] -to [get_cells u_gray_bus/u_gray_sync/* -filter {IS_SEQUENTIAL}]
set_max_delay -datapath_only 7.5 -from [get_cells u_handshake/* -filter {IS_SEQUENTIAL}] -to [get_cells u_handshake/* -filter {IS_SEQUENTIAL}]
set_bus_skew 7.5 -from [get_cells u_handshake/* -filter {IS_SEQUENTIAL}] -to [get_cells u_handshake/* -filter {IS_SEQUENTIAL}]
set_max_delay -datapath_only 7.5 -from [get_cells u_handshake/* -filter {IS_SEQUENTIAL}] -to [get_cells u_handshake/u_sync_req/* -filter {IS_SEQUENTIAL}]
set_max_delay -datapath_only 10.0 -from [get_cells u_handshake/* -filter {IS_SEQUENTIAL}] -to [get_cells u_handshake/u_sync_ack/* -filter {IS_SEQUENTIAL}]
